const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=fs.readFileSync('script.js','utf8');
const context=vm.createContext({console,URLSearchParams,navigator:{},window:{location:{search:''}},document:{addEventListener(){},getElementById(){return null}},setTimeout,clearTimeout});
vm.runInContext(source,context);
const run=code=>vm.runInContext(code,context);
function seed(rows,photos=[],matches=[]){
 context.fixture={rows,photos,matches};
 run(`appData={playerTeams:fixture.rows,players:fixture.photos,allMatches:fixture.matches,matches:[],myGames:[]};playerTeamsLookup=buildPlayerTeamsLookup(appData.playerTeams);playerImageLookup=buildPlayerImageLookup(appData.players);playerAliasLookup=buildPlayerAliasLookup();`);
}
const raya={ 'Player Name':'David Raya',Season:2027,Team:'Arsenal',Position:'GK','Team Type':'Club',Status:'Active'};
seed([raya],[{'Player Name':'D. Raya','Player Image URL':'raya.png'}]);
assert.equal(run(`canonicalPlayerName('D. Raya')`),'David Raya');
assert.equal(run(`getPlayerImageUrl('David Raya')`),'raya.png');
assert.equal(run(`findSearchPlayers(getMasterSearchItems().players,'Raya').join()`),'David Raya');
assert.match(run(`renderPlayerSearchLabel('David Raya')`),/Arsenal · GK/);
assert.doesNotMatch(run(`renderPlayerProfile('D. Raya',2027)`),/player-summary-grid|Dates not restricted/);
seed([raya,{...raya,'Player Name':'Daniel Raya'}],[{'Player Name':'D. Raya','Player Image URL':'ambiguous.png'}]);
assert.equal(run(`canonicalPlayerName('D. Raya')`),'D. Raya');
assert.equal(run(`getPlayerImageUrl('David Raya')`),'');
seed([raya],[{'Player Name':'Daniel Raya','Player Image URL':'wrong.png'},{'Player Name':'David Raya','Player Image URL':'exact.png'},{'Player Name':'D. Raya','Player Image URL':'alias.png'}]);
assert.equal(run(`getPlayerImageUrl('David Raya')`),'exact.png');
assert.equal(run(`canonicalPlayerName('Daniel Raya')`),'Daniel Raya');
const match=(id,year,status,team='Arsenal')=>({MatchID:id,Year:year,Date:'2026-09-20',HomeTeam:team,AwayTeam:'Chelsea',Status:status,HomeScore:2,AwayScore:1});
seed([raya,{...raya,Season:2026,Team:'Brentford'},{...raya,Team:'Spain','Team Type':'National Team'}],[],[match('club',2027,'FT'),match('national',2027,'FT','Spain'),match('old',2026,'FT','Brentford'),match('live',2027,'LIVE'),match('scheduled',2027,'NS'),match('wrong-season',2026,'FT')]);
assert.equal(run(`getPlayerMatches(getPlayerSeasonRows('D. Raya',2027),'David Raya').map(x=>x.match.MatchID).sort().join()`),'club,national');
assert.equal(run(`getTeamSquad('Arsenal',2026).length`),0);
assert.equal(run(`getTeamSquad('Arsenal',2027).length`),1);
assert.equal(run(`getPlayerMatches(getPlayerSeasonRows('David Raya',2026),'David Raya')[0].match.MatchID`),'old');
assert.match(run(`renderTeamSquad('Arsenal',2027)`),/openPlayerProfile\(&quot;David Raya&quot;,null,&quot;2027&quot;\)/);
assert.equal(run(`getProfileMatchSeason({Year:2027,Date:'2025-01-01'})`),'2027');
assert.equal(run(`getProfileMatchSeason({Date:'2026-09-20'})`),'2027');
assert.equal(run(`normaliseProfileSeason('2026/27')`),'2027');
assert.match(run(`renderPlayerProfile('David Raya',2026)`),/Brentford/);
assert.doesNotMatch(run(`renderPlayerProfile('David Raya',2026)`),/>Arsenal</);
seed([raya],[],[]);
run(`appData.selectedCompetition={Year:2027,'Competition Name':'Premier League'};appData.matches=[{MatchID:'local',HomeTeam:'Arsenal',AwayTeam:'Chelsea',Status:'FT',Date:'2025-01-01'}];`);
assert.equal(run(`getProfileMatches()[0].Year`),2027);
assert.equal(run(`appData.matches[0].Year`),undefined);
assert.equal(run(`getPlayerMatches(getPlayerSeasonRows('David Raya',2027),'David Raya').length`),1);
seed([{...raya,'Player Name':'João Félix'}],[{'Player Name':'J. Felix','Player Image URL':'felix.png'}]);
assert.equal(run(`getPlayerImageUrl('Joao Felix')`),'felix.png');
if(process.env.CALCIUM_LIVE_FIXTURES){
 const rows=JSON.parse(fs.readFileSync('/tmp/calcium-playerDatabase.json')).playerTeams;
 const hub=JSON.parse(fs.readFileSync('/tmp/calcium-hubData.json'));
 seed(rows,hub.players);
 assert.equal(run(`findSearchPlayers(getMasterSearchItems().players,'Raya').join()`),'David Raya');
 assert.equal(run(`getPlayerImageUrl('David Raya')`),'https://static.flashscore.com/res/image/data/h0Kr6yzB-baq9bltG.png');
 assert.equal(run(`getTeamSquad('Arsenal',2027).length`),30);
 const home=JSON.parse(fs.readFileSync('/tmp/calcium-home-retry.json'));
 context.liveHome=home;
 run(`appData.allMatches=liveHome.allGames.map(mapApiMatchToPascal);appData.myGames=liveHome.myGames.map(mapApiMatchToPascal);`);
 const expected=home.allGames.filter(m=>m.status==='FT'&&String(m.year)==='2027'&&[m.homeTeam,m.awayTeam].includes('Arsenal')).map(m=>m.matchId).sort().join();
 assert.equal(run(`getPlayerMatches(getPlayerSeasonRows('David Raya',2027),'David Raya').map(x=>x.match.MatchID).sort().join()`),expected);
 console.log('Live Arsenal 2027 FT matches:',expected.split(',').length);
 console.log('Live database: Raya → David Raya, Arsenal, GK, existing photo; Arsenal squad: 30.');
}
console.log('Player identity, collisions, photos, seasons, FT games and squad tests passed.');
